# Zenbones
[colors]
foreground = "#2C363C"
background = "#F0EDEC"
cursor_bg = "#2C363C"
cursor_border = "#F2F0EF"
cursor_fg = "#F2F0EF"
selection_bg = "#D2DFE7"
selection_fg = "#2C363C"

ansi = ["#F0EDEC", "#A8334C", "#617437", "#944927", "#286486", "#88507D", "#3B8992", "#2C363C"]
brights = ["#DCD2CE", "#9C2842", "#55672A", "#87411E", "#1F5A7A", "#864079", "#2F7C85", "#44525B"]
