# Zenflesh
[colors]
foreground = "#B3BABF"
background = "#1A1715"
cursor_bg = "#C2C7CB"
cursor_border = "#161311"
cursor_fg = "#161311"
selection_bg = "#303B41"
selection_fg = "#B3BABF"

ansi = ["#1A1715", "#BB6572", "#75884C", "#B86E54", "#4185AE", "#AC75A1", "#4F969E", "#B3BABF"]
brights = ["#2F2925", "#D16D7D", "#7F974C", "#D07654", "#4293C2", "#C873B8", "#4CA2AC", "#93999E"]
