name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    - uses: actions/checkout@v2
    - uses: NTBBloodbath/selene-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: lua
